# -*- coding: utf-8 -*-
"""ns project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5KZFpEVXWn6LyHUJICQprMD9PtpnsI0
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('/content/Meteorite_Landings (2).csv')

df.describe()

# Select required columns
selected_df = df[['recclass', 'mass (g)', 'year', 'reclat', 'reclong', 'GeoLocation']]

selected_df = df[['recclass', 'mass (g)', 'year', 'reclat', 'reclong', 'GeoLocation']]

null_summary = pd.DataFrame({
    'Null Count': selected_df.isnull().sum(),
    'Null Percentage': (selected_df.isnull().sum() / len(selected_df)) * 100
})

null_summary['Null Percentage'] = null_summary['Null Percentage'].round(2)

print(null_summary)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10, 8))
correlation_matrix = selected_df.corr(numeric_only=True)
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Heatmap of Meteorite Dataset Features', fontsize=14, fontweight='bold')
plt.show()

# Remove rows with null values
clean_df = selected_df.dropna()

# Check result
print("Original shape:", selected_df.shape)
print("After removing null values:", clean_df.shape)

# Display first 5 rows
print(clean_df.head())

null_percentage = (
    clean_df[['recclass', 'mass (g)', 'year', 'reclat', 'reclong', 'GeoLocation']]
    .isnull()
    .sum()
    / len(clean_df)
) * 100

print(null_percentage)

clean_df.describe()

# Remove rows where mass is null
df_clean = df.dropna(subset=['mass (g)'])

# Convert mass to numeric
df_clean['mass (g)'] = pd.to_numeric(df_clean['mass (g)'], errors='coerce')

# Plot histogram
plt.figure(figsize=(10,6))
plt.hist(df_clean['mass (g)'], bins=30)
plt.title('Mass Distribution After Removing Null Values')
plt.xlabel('Mass (g)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

import numpy as np

mass = df_clean['mass (g)']
mass = mass[mass > 0]

plt.figure(figsize=(10,6))
plt.hist(np.log10(mass), bins=30)
plt.title('Log-Scaled Mass Distribution')
plt.xlabel('log10(Mass (g))')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(15, 7))

min_year = int(clean_df['year'].min())
max_year = int(clean_df['year'].max())
bin_edges = np.arange(min_year, max_year + 5, 5)

plt.hist(clean_df['year'], bins=bin_edges, color='skyblue', edgecolor='black', alpha=0.8)

plt.xticks(np.arange(min_year, max_year + 25, 25), rotation=45)

plt.title('Meteorite Landing Years Distribution (5-Year Intervals)', fontsize=14, fontweight='bold')
plt.xlabel('Year (5-Year Bins)', fontsize=12)
plt.ylabel('Frequency (Count)', fontsize=12)

plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

# First, convert year to numeric (in case there are non-numeric values)
clean_df['year'] = pd.to_numeric(clean_df['year'], errors='coerce')

# Remove rows where year is 2025 or greater (keep only years < 2025)
clean_df = clean_df[clean_df['year'] < 2025]

print("After year filter (year < 2025) - shape:", clean_df.shape)



# Remove mass values that are 0 or less (keep only positive mass)
clean_df = clean_df[clean_df['mass (g)'] > 0]

print("After mass filter (mass > 0) - shape:", clean_df.shape)

# Remove any rows that might have become NaN after conversions
clean_df = clean_df.dropna()

print("Final shape after all filters:", clean_df.shape)

clean_df.describe()

zero_coords = df[(df['reclat'] == 0) & (df['reclong'] == 0)]

print("Records with (0,0):", len(zero_coords))

print(zero_coords[['name', 'recclass', 'reclat', 'reclong']].head())

import pandas as pd

# 1. Total rows remaining
print("Total records after cleaning:", len(clean_df))

# 2. Number of unique recclass types
print("Number of unique recclass types:", clean_df['recclass'].nunique())

# 3. Count of each recclass
recclass_counts = clean_df['recclass'].value_counts()

print("\nRecclass counts:")
print(recclass_counts)

print(clean_df['recclass'].value_counts().head(20))

import matplotlib.pyplot as plt

top10 = clean_df['recclass'].value_counts().head(10)

plt.figure(figsize=(12,6))
top10.plot(kind='bar')
plt.title('Top 10 Meteorite Classes After Cleaning')
plt.xlabel('Recclass')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
# මහාද්වීප අනුව උල්කාපාත සංඛ්‍යාව පෙන්වන ප්‍රස්ථාරය
sns.countplot(x='continent', data=clean_df, order=clean_df['continent'].value_counts().index, palette='viridis')
plt.title('Distribution of Meteorite Landings by Continent')
plt.xlabel('Continent')
plt.ylabel('Number of Landings')
plt.xticks(rotation=45)
plt.show()

clean_df.info()

# Top recclass categories
major_classes = [
    'L6',
    'H5',
    'H6',
    'L5',
    'LL5',
    'H4',
    'LL6',
    'L4'
]

# Group rare classes into Other
clean_df['recclass_grouped'] = clean_df['recclass'].apply(
    lambda x: x if x in major_classes else 'Other'
)

# Check distribution
print(clean_df['recclass_grouped'].value_counts())

# Keep final columns
final_df = clean_df[
    ['recclass_grouped', 'year', 'reclat', 'reclong', 'GeoLocation']
]

print(final_df.shape)
print(final_df.head())

#  Lat/Long අනුව මහාද්වීපය (Continent) වෙන් කරන සරල ශ්‍රිතය (Function)
def get_continent(lat, lon):
    if lat < -60:
        return 'Antarctica'
    elif lat > 10 and -170 < lon < -50:
        return 'North America'
    elif lat < 10 and -90 < lon < -30:
        return 'South America'
    elif lat > 35 and -10 < lon < 40:
        return 'Europe'
    elif lat > -35 and 10 < lon < 55:
        return 'Africa'
    elif lat > -10 and 60 < lon < 150:
        return 'Asia'
    elif lat < 0 and 110 < lon < 180:
        return 'Oceania/Australia'
    else:
        return 'Other/Ocean'

clean_df['continent'] = clean_df.apply(lambda row: get_continent(row['reclat'], row['reclong']), axis=1)

clean_df.head()

"""# **Hypothesis Test 01: උල්කාපාතවල ස්කන්ධය සහ ඒවා වැටුණු වර්ෂය අතර සම්බන්ධයක් තිබේද? (Spearman Correlation Test)**"""

from scipy import stats

# Null and Alternative Hypotheses
print("Hypothesis Test 1: Correlation between Mass and Year")
print("H0 (Null Hypothesis): There is no correlation between meteorite mass and the year it was found.")
print("H1 (Alternative Hypothesis): There is a significant correlation between meteorite mass and the year it was found.")

# Cleaning data for test (removing NaNs)
hyp1_data = df[['mass (g)', 'year']].dropna()

# Performing Spearman Test
correlation, p_value = stats.spearmanr(hyp1_data['mass (g)'], hyp1_data['year'])

print(f"p-value: {p_value}")

# Conclusion
alpha = 0.05
if p_value < alpha:
    print("Conclusion: Reject the Null Hypothesis (H0). There is a significant correlation between mass and year.")
else:
    print("Conclusion: Fail to reject the Null Hypothesis (H0). There is no significant correlation between mass and year.")

"""# **Hypothesis Test 02: මහාද්වීප අනුව උල්කාපාතවල සාමාන්‍ය ස්කන්ධයන්ගේ පැහැදිලි වෙනසක් පවතීද? (Kruskal-Wallis Test)**"""

print("\nHypothesis Test 2: Comparison of Meteorite Mass Across Continents")
print("H0 (Null Hypothesis): The distribution of meteorite mass is the same across all continents.")
print("H1 (Alternative Hypothesis): The distribution of meteorite mass is different for at least one continent.")

# Preparing data grouping by continent
continents = clean_df['continent'].unique()
groups = [clean_df[clean_df['continent'] == cont]['mass (g)'].dropna() for cont in continents if pd.notna(cont)]

# Performing Kruskal-Wallis Test
stat, p_value2 = stats.kruskal(*groups)

print(f"p-value: {p_value2}")

# Conclusion
if p_value2 < alpha:
    print("Conclusion: Reject the Null Hypothesis (H0). The mass of meteorites varies significantly across different continents.")
else:
    print("Conclusion: Fail to reject the Null Hypothesis (H0). There is no significant difference in mass across continents.")

"""# **උල්කාපාත කඩා වැටුණු හෝ සොයාගත් වර්ෂය (year) සහ මහාද්වීපය (continent) අතර සම්බන්ධතාවයක් (Statistical Relationship) පවතීද**"""

print("Hypothesis Test 3: Comparison of Year Across Continents")
print("H0 (Null Hypothesis): The distribution of the year meteorites were found is the same across all continents.")
print("H1 (Alternative Hypothesis): The distribution of the year meteorites were found is different for at least one continent.")

# Preparing data grouping by continent for 'year'
year_groups = [clean_df[clean_df['continent'] == cont]['year'].dropna() for cont in continents if pd.notna(cont)]

# Performing Kruskal-Wallis Test
stat3, p_value3 = stats.kruskal(*year_groups)

print(f"p-value: {p_value3}")

if p_value3 < alpha:
    print("Conclusion: Reject the Null Hypothesis (H0). The year of meteorite landings varies significantly across different continents.")
else:
    print("Conclusion: Fail to reject the Null Hypothesis (H0). There is no significant difference in the landing years across continents.")

print("=== SMOTE  ===")
print(clean_df['continent'].value_counts())

y = clean_df['continent']

X = clean_df[["recclass", "mass (g)", "year"]].copy()

from sklearn.preprocessing import LabelEncoder

le_X = LabelEncoder()
X['recclass'] = le_X.fit_transform(X['recclass'])

le_y = LabelEncoder()
y_encoded = le_y.fit_transform(y)

le_y = LabelEncoder()
y_encoded = le_y.fit_transform(y)

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

from collections import Counter

print(f"\nTrain කිරීමට පෙර තිබූ දත්ත ප්‍රමාණය: {Counter(y_train)}")

from imblearn.over_sampling import SMOTE
from collections import Counter

# Impute missing values in X_train before applying SMOTE
# Calculate median of 'mass (g)' from X_train
median_mass_g = X_train['mass (g)'].median()
X_train['mass (g)'] = X_train['mass (g)'].fillna(median_mass_g)

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print(f"\n=== SMOTE කිරීමෙන් පසු සමබර වූ දත්ත ප්‍රමාණය ===")
print(Counter(y_train_resampled))

"""# **RandomForestClassifier**"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

model = RandomForestClassifier(n_estimators=100, random_state=42)


model.fit(X_train_resampled, y_train_resampled)
print("Model training completed!")



y_pred = model.predict(X_test)

#  (Accuracy)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy : {accuracy * 100:.2f}%")

print(" (Classification Report) ")


continent_labels = le_y.classes_
print(classification_report(y_test, y_pred, target_names=continent_labels))

print("Confusion Matrix")

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=continent_labels, yticklabels=continent_labels)
plt.xlabel('Predicted Continent')
plt.ylabel('Actual Continent ')
plt.title('Confusion Matrix - Meteorite Landing Prediction')
plt.show()

# Training Accuracy
# ==========================
train_pred = model.predict(X_train_resampled)
train_acc = accuracy_score(y_train_resampled, train_pred)

# Testing Accuracy
# ==========================
y_pred = model.predict(X_test)
test_acc = accuracy_score(y_test, y_pred)

print(f"Training Accuracy: {train_acc * 100:.2f}%")
print(f"Testing Accuracy: {test_acc * 100:.2f}%")

print(classification_report(y_test, y_pred))

"""# **GRADIENT BOOSTING CLASSIFIER MODEL**"""

from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train_resampled, y_train_resampled)

y_pred_gb = gb_model.predict(X_test)
gb_accuracy = accuracy_score(y_test, y_pred_gb)
print(f" Gradient Boosting Accuracy: {gb_accuracy * 100:.2f}%\n")

# Training Accuracy
# ==========================
train_pred = gb_model.predict(X_train_resampled)
train_acc = accuracy_score(y_train_resampled, train_pred)

# ==========================
# Testing Accuracy
# ==========================
y_pred = gb_model.predict(X_test)
test_acc = accuracy_score(y_test, y_pred)

print(f"Training Accuracy: {train_acc * 100:.2f}%")
print(f"Testing Accuracy: {test_acc * 100:.2f}%")

print(classification_report(y_test, y_pred_gb))

"""# **K-NEAREST NEIGHBORS (KNN) MODEL**"""

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_resampled, y_train_resampled)


y_pred_knn = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test, y_pred_knn)
print(f" KNN Accuracy: {knn_accuracy * 100:.2f}%\n")

# Training Accuracy
# ==========================
train_pred_knn = knn_model.predict(X_train_resampled)
train_acc_knn = accuracy_score(y_train_resampled, train_pred_knn)

# ==========================
# Testing Accuracy
# ==========================
y_pred_knn = knn_model.predict(X_test)
test_acc_knn = accuracy_score(y_test, y_pred_knn)

print(f"Training Accuracy: {train_acc_knn * 100:.2f}%")
print(f"Testing Accuracy: {test_acc_knn * 100:.2f}%")

print(classification_report(y_test, y_pred_knn))

"""# **XGBoost Classifier**"""

!pip install xgboost
from xgboost import XGBClassifier

# --- MODEL 2: XGBoost Classifier ---
print("--- Training XGBoost Classifier ---")
# eval_metric='mlogloss' යොදන්නේ Multi-class ගැටලුවක් නිසා වැරදි අනතුරු ඇඟවීම් (warnings) නැති කිරීමටයි
xgb_model = XGBClassifier(
    random_state=42, n_estimators=100, max_depth=6, eval_metric="mlogloss"
)
xgb_model.fit(X_train_resampled, y_train_resampled)

xgb_pred = xgb_model.predict(X_test)
xgb_acc = accuracy_score(y_test, xgb_pred)
print(f"XGBoost Accuracy: {xgb_acc * 100:.2f}%\n")

# ==========================
# Training Accuracy
# ==========================
train_pred = xgb_model.predict(X_train_resampled)
train_acc = accuracy_score(y_train_resampled, train_pred)

# ==========================
# Testing Accuracy
# ==========================
xgb_pred = xgb_model.predict(X_test)
test_acc = accuracy_score(y_test, xgb_pred)

print(f"Training Accuracy: {train_acc * 100:.2f}%")
print(f"Testing Accuracy: {test_acc * 100:.2f}%")

print(classification_report(y_test, xgb_pred))

"""# ***LightGBM Classifier***"""

from lightgbm import LGBMClassifier

# --- MODEL 3: LightGBM Classifier ---
print("--- Training LightGBM Classifier ---")
lgb_model = LGBMClassifier(
    random_state=42, n_estimators=100, max_depth=6, verbosity=-1
)
lgb_model.fit(X_train_resampled, y_train_resampled)

lgb_pred = lgb_model.predict(X_test)
lgb_acc = accuracy_score(y_test, lgb_pred)
print(f"LightGBM Accuracy: {lgb_acc * 100:.2f}%\n")

# ==========================
# Training Accuracy
# ==========================
train_pred_lgb = lgb_model.predict(X_train_resampled)
train_acc_lgb = accuracy_score(y_train_resampled, train_pred_lgb)

# ==========================
# Testing Accuracy
# ==========================
lgb_pred = lgb_model.predict(X_test)
test_acc_lgb = accuracy_score(y_test, lgb_pred)

print(f"Training Accuracy: {train_acc_lgb * 100:.2f}%")
print(f"Testing Accuracy: {test_acc_lgb * 100:.2f}%")

print(classification_report(y_test, lgb_pred))